@echo off
@del /q *.o *.bin *.dbg *.map

SETLOCAL

:: Stock FamiTone2
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FT_NTSC_SUPPORT=1", nsf_famitone2_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FT_PAL_SUPPORT=1", nsf_famitone2_pal
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FT_NTSC_SUPPORT=1 -D FT_PAL_SUPPORT=1", nsf_famitone2_dual

:: FamiStudio engine (FamiTracker tempo)
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1", nsf_famistudio_famitracker_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_PAL_SUPPORT=1", nsf_famistudio_famitracker_pal
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_CFG_PAL_SUPPORT=1", nsf_famistudio_famitracker_dual
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_VRC6=1", nsf_famistudio_famitracker_vrc6_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_VRC7=1", nsf_famistudio_famitracker_vrc7_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_MMC5=1", nsf_famistudio_famitracker_mmc5_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_S5B=1", nsf_famistudio_famitracker_s5b_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_FDS=1", nsf_famistudio_famitracker_fds_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=1", nsf_famistudio_famitracker_n163_1ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=2", nsf_famistudio_famitracker_n163_2ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=3", nsf_famistudio_famitracker_n163_3ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=4", nsf_famistudio_famitracker_n163_4ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=5", nsf_famistudio_famitracker_n163_5ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=6", nsf_famistudio_famitracker_n163_6ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=7", nsf_famistudio_famitracker_n163_7ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=8", nsf_famistudio_famitracker_n163_8ch_ntsc

:: FamiStudio engine (FamiStudio tempo)
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1", nsf_famistudio_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_PAL_SUPPORT=1", nsf_famistudio_pal
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_CFG_PAL_SUPPORT=1", nsf_famistudio_dual
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_VRC6=1", nsf_famistudio_vrc6_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_VRC7=1", nsf_famistudio_vrc7_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_MMC5=1", nsf_famistudio_mmc5_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_S5B=1", nsf_famistudio_s5b_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_FDS=1", nsf_famistudio_fds_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=1", nsf_famistudio_n163_1ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=2", nsf_famistudio_n163_2ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=3", nsf_famistudio_n163_3ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=4", nsf_famistudio_n163_4ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=5", nsf_famistudio_n163_5ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=6", nsf_famistudio_n163_6ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=7", nsf_famistudio_n163_7ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=1", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_EXP_N163=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=8", nsf_famistudio_n163_8ch_ntsc

:: FamiStudio Multi-expansion Engine (FamiTracker tempo)
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=1", nsf_famistudio_famitracker_multi_n163_1ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=2", nsf_famistudio_famitracker_multi_n163_2ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=3", nsf_famistudio_famitracker_multi_n163_3ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=4", nsf_famistudio_famitracker_multi_n163_4ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=5", nsf_famistudio_famitracker_multi_n163_5ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=6", nsf_famistudio_famitracker_multi_n163_6ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=7", nsf_famistudio_famitracker_multi_n163_7ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=8", nsf_famistudio_famitracker_multi_n163_8ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=1 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_multi_n163_1ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=2 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_multi_n163_2ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=3 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_multi_n163_3ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=4 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_multi_n163_4ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=5 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_multi_n163_5ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=6 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_multi_n163_6ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=7 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_multi_n163_7ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_USE_FAMITRACKER_TEMPO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=8 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_famitracker_multi_n163_8ch_epsm_ntsc

:: FamiStudio Multi-expansion Engine (FamiStudio tempo)
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=1", nsf_famistudio_multi_n163_1ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=2", nsf_famistudio_multi_n163_2ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=3", nsf_famistudio_multi_n163_3ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=4", nsf_famistudio_multi_n163_4ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=5", nsf_famistudio_multi_n163_5ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=6", nsf_famistudio_multi_n163_6ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=7", nsf_famistudio_multi_n163_7ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=2", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=8", nsf_famistudio_multi_n163_8ch_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=1 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_multi_n163_1ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=2 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_multi_n163_2ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=3 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_multi_n163_3ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=4 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_multi_n163_4ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=5 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_multi_n163_5ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=6 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_multi_n163_6ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=7 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_multi_n163_7ch_epsm_ntsc
CALL :CompileNsfPermutation nsf.cfg, "{CODEBANKS}=3", "-D FAMISTUDIO=1 -D FAMISTUDIO_CFG_NTSC_SUPPORT=1 -D FAMISTUDIO_MULTI_EXPANSION=1 -D FAMISTUDIO_EXP_N163_CHN_CNT=8 -D FAMISTUDIO_EXP_EPSM=1", nsf_famistudio_multi_n163_8ch_epsm_ntsc

EXIT /B %ERRORLEVEL%

:CompileNsfPermutation
@echo %~4
PatchText %~1 tmp.cfg %~2
..\..\Tools\ca65 nsf.s -g -o %~4.o %~3 
..\..\Tools\ld65 -C tmp.cfg -o %~4.bin %~4.o --mapfile %~4.map --dbgfile %~4.dbg
PrintCodeSize %~4.bin %~2
ExtractNoteTable %~4.dbg %~2
del tmp.cfg
EXIT /B 0
