;this file for FamiTone2 library generated by FamiStudio

journey_to_silius_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env5), .hibyte(@tempo_env5), 0, 0

@instruments:
	.word @env2,@env0,@env0,@env4
	.word @env3,@env0,@env0,@env4
	.word @env11,@env0,@env0,@env8
	.word @env16,@env0,@env0,@env8
	.word @env3,@env0,@env12,@env4
	.word @env7,@env0,@env12,@env8
	.word @env5,@env0,@env9,@env4
	.word @env16,@env0,@env9,@env8
	.word @env6,@env13,@env0,@env8
	.word @env15,@env14,@env0,@env8
	.word @env6,@env14,@env0,@env8
	.word @env1,@env10,@env0,@env8
	.word @env1,@env0,@env0,@env8

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0c	;1 (Sample 1)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0a	;2 (Sample 1)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0e	;3 (Sample 1)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$09	;4 (Sample 1)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3e,$0d	;5 (Sample 2)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3e,$08	;6 (Sample 2)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0d	;7 (Sample 3)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0f	;8 (Sample 1)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3e,$0c	;9 (Sample 4)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$3e,$0f	;10 (Sample 4)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3e,$0a	;11 (Sample 2)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3e,$0e	;12 (Sample 2)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0a	;13 (Sample 5)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0e	;14 (Sample 5)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$3f,$0e	;15 (Sample 3)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;16 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;17 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;18 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;19 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;20 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;21 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;22 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;23 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;24 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;25 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;26 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;27 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;28 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;29 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;30 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;31 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;32 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;33 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;34 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;35 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;36 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;37 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;38 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;39 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;40 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;41 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;42 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;43 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;44 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;45 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;46 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;47 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;48 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;49 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;50 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;51 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;52 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;53 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;54 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;55 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;56 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;57 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;58 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;59 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;60 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;61 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;62 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;63 

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $04,$cf,$7f,$00,$01
@env2:
	.byte $08,$ce,$cb,$ca,$c9,$c9,$00,$05,$c1,$c5,$c4,$c3,$c2,$c1,$00,$0d
@env3:
	.byte $0f,$c4,$c6,$c9,$c8,$0e,$c7,$0e,$c6,$0e,$c5,$0e,$c4,$00,$0c,$c1,$c5,$c4,$c3,$c2,$c1,$00,$14
@env4:
	.byte $00,$c0,$07,$c1,$c3,$c6,$c3,$c1,$bf,$bd,$ba,$bd,$bf,$00,$03
@env5:
	.byte $0e,$c5,$c6,$c6,$ca,$cb,$cc,$cb,$ca,$c9,$c8,$c7,$00,$0b,$c1,$c5,$c4,$c3,$c2,$c1,$00,$13
@env6:
	.byte $00,$cc,$cc,$c9,$c5,$c2,$c0,$00,$06
@env7:
	.byte $04,$c3,$7f,$00,$01
@env8:
	.byte $00,$c0,$7f,$00,$01
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$00,$09
@env11:
	.byte $00,$c5,$c9,$c9,$c8,$00,$04
@env12:
	.byte $c1,$7f,$00,$00
@env13:
	.byte $c0,$c3,$00,$01
@env14:
	.byte $c0,$c6,$00,$01
@env15:
	.byte $00,$cd,$ce,$cc,$c8,$c9,$c7,$c6,$c4,$c3,$c1,$c0,$00,$0b
@env16:
	.byte $04,$c4,$7f,$00,$01
@env17:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@tempo_env5:
	.byte $06,$04,$04,$04,$04,$09,$80

@song0ch0:
@ref0:
	.byte $cf
@song0ch0loop:
@ref1:
	.byte $fb,.lobyte(@tempo_env5),.hibyte(@tempo_env5),$00,$a5,$8a,$25,$91,$28,$91,$25,$91,$2a,$2b,$81,$2c,$9f,$2a,$91
@ref2:
	.byte $82,$20,$af,$f9,$87,$22,$d7,$f9,$87
@ref3:
	.byte $00,$a5,$8a,$25,$91,$28,$91,$25,$91,$2a,$2b,$81,$2c,$9f,$2a,$91
@ref4:
	.byte $82,$2c,$af,$f9,$87,$2a,$d7,$f9,$87
	.byte $ff,$0f
	.word @ref3
	.byte $ff,$08
	.word @ref2
	.byte $ff,$0f
	.word @ref3
	.byte $ff,$08
	.word @ref4
@ref5:
	.byte $a7,$23,$91,$f9,$91,$22,$87,$f9,$87,$23,$91,$f9,$91,$23,$91
@ref6:
	.byte $93,$f9,$91,$22,$91,$f9,$91,$22,$87,$f9,$87,$23,$87,$f9,$af
	.byte $ff,$0f
	.word @ref5
	.byte $ff,$0f
	.word @ref6
	.byte $ff,$0f
	.word @ref5
	.byte $ff,$0f
	.word @ref6
@ref7:
	.byte $a7,$23,$91,$f9,$91,$22,$87,$f9,$87,$23,$91,$f9,$91,$20,$91
@ref8:
	.byte $f7,$89,$f9,$87,$8c,$25,$91
@ref9:
	.byte $89,$f9,$87,$25,$87,$f9,$87,$28,$87,$f9,$87,$25,$87,$f9,$87,$2a,$87,$f9,$87,$25,$91,$f9,$91,$2c,$91
@ref10:
	.byte $89,$f9,$87,$25,$87,$f9,$87,$2a,$87,$f9,$87,$25,$87,$f9,$87,$28,$87,$f9,$87,$25,$91,$f9,$91,$20,$91
@ref11:
	.byte $89,$f9,$87,$20,$87,$f9,$87,$23,$87,$f9,$87,$20,$87,$f9,$87,$23,$87,$f9,$87,$26,$62,$27,$81,$62,$28,$8b,$27,$87,$f9,$87,$25,$91
@ref12:
	.byte $f7,$89,$f9,$87,$25,$91
@ref13:
	.byte $89,$f9,$87,$25,$87,$f9,$87,$28,$87,$f9,$87,$25,$87,$f9,$87,$2a,$87,$f9,$87,$25,$91,$f9,$91,$2a,$62,$2b,$81,$62,$2c,$8b
@ref14:
	.byte $93,$25,$87,$f9,$87,$2a,$87,$f9,$87,$25,$87,$f9,$87,$28,$87,$f9,$87,$25,$91,$f9,$91,$20,$91
@ref15:
	.byte $89,$f9,$87,$20,$87,$f9,$87,$23,$87,$f9,$87,$25,$87,$f9,$87,$26,$62,$27,$81,$62,$28,$8b,$27,$87,$f9,$87,$23,$87,$f9,$87,$25,$91
@ref16:
	.byte $f7,$9d,$f9,$87
@ref17:
	.byte $2a,$81,$62,$2b,$81,$62,$2c,$d9,$2a,$87,$f9,$87,$28,$87,$f9,$87,$27,$91
@ref18:
	.byte $c5,$f9,$87,$28,$91,$f9,$87,$2a,$91,$f9,$87,$2a,$62,$2b,$81,$62,$2c,$8b
@ref19:
	.byte $f7,$93,$88,$2a,$62,$2b,$81,$62,$2c,$8b
@ref20:
	.byte $93,$2a,$62,$2b,$81,$62,$2c,$8b,$2e,$91,$f9,$91,$2f,$9b,$f9,$af
@ref21:
	.byte $8c,$2a,$81,$62,$2b,$81,$62,$2c,$d9,$2a,$87,$f9,$87,$28,$87,$f9,$87,$27,$91
@ref22:
	.byte $c5,$f9,$87,$28,$91,$f9,$87,$2a,$91,$f9,$87,$25,$91
@ref23:
	.byte $f7,$a7
@ref24:
	.byte $93,$80,$25,$87,$f9,$87,$25,$87,$f9,$87,$25,$87,$f9,$87,$25,$87,$f9,$c3
@ref25:
	.byte $82,$25,$c3,$f9,$87,$25,$c3,$f9,$87
@ref26:
	.byte $25,$af,$f9,$87,$25,$cd,$f9,$91
@ref27:
	.byte $25,$c3,$f9,$87,$25,$c3,$f9,$87
	.byte $ff,$08
	.word @ref26
	.byte $ff,$08
	.word @ref27
	.byte $ff,$08
	.word @ref26
@ref28:
	.byte $27,$c3,$f9,$87,$27,$c3,$f9,$87
@ref29:
	.byte $27,$af,$f9,$87,$27,$cd,$f9,$91
@ref30:
	.byte $25,$9b,$f9,$87,$25,$9b,$f9,$87,$25,$91,$f9,$87,$25,$91,$f9,$87,$25,$91
@ref31:
	.byte $9d,$f9,$87,$25,$9b,$f9,$87,$25,$91,$f9,$87,$25,$91,$f9,$87,$25,$91
	.byte $ff,$11
	.word @ref31
@ref32:
	.byte $b1,$f9,$87,$23,$c3,$f9,$87,$25,$91
	.byte $ff,$11
	.word @ref31
	.byte $ff,$11
	.word @ref31
@ref33:
	.byte $9d,$f9,$87,$25,$9b,$f9,$87,$27,$91,$f9,$87,$2c,$91,$f9,$87,$2c,$91
@ref34:
	.byte $f7,$9d,$f9,$87
@ref35:
	.byte $00,$a5,$86,$25,$91,$27,$91,$28,$91,$2a,$91,$25,$91,$27,$91
@ref36:
	.byte $28,$91,$2a,$91,$25,$91,$27,$91,$28,$91,$2a,$91,$25,$91,$27,$91
	.byte $ff,$10
	.word @ref36
	.byte $ff,$10
	.word @ref36
	.byte $ff,$10
	.word @ref36
@ref37:
	.byte $28,$91,$2a,$91,$27,$91,$28,$91,$2a,$91,$2c,$b9
@ref38:
	.byte $2f,$91,$31,$a5,$33,$91,$34,$91,$36,$91,$31,$91,$33,$91
@ref39:
	.byte $34,$91,$36,$a5,$38,$91,$39,$91,$3b,$91,$36,$91,$38,$91
@ref40:
	.byte $39,$91,$3b,$91,$3d,$f5
@ref41:
	.byte $f7,$62,$61,$05,$3d,$37,$a5
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref42:
	.byte $cf
@song0ch1loop:
@ref43:
	.byte $88,$25,$87,$f9,$87,$28,$87,$f9,$87,$25,$87,$f9,$87,$2a,$62,$2b,$81,$62,$2c,$9f,$2a,$87,$f9,$87,$28,$9b,$f9,$87
@ref44:
	.byte $23,$af,$f9,$87,$25,$d7,$f9,$87
@ref45:
	.byte $25,$87,$f9,$87,$28,$87,$f9,$87,$25,$87,$f9,$87,$2a,$62,$2b,$81,$62,$2c,$9f,$2a,$87,$f9,$87,$28,$9b,$f9,$87
@ref46:
	.byte $2f,$af,$f9,$87,$2e,$d7,$f9,$87
	.byte $ff,$19
	.word @ref45
	.byte $ff,$08
	.word @ref44
	.byte $ff,$19
	.word @ref45
	.byte $ff,$08
	.word @ref46
@ref47:
	.byte $a7,$82,$28,$91,$f9,$91,$27,$87,$f9,$87,$28,$91,$f9,$91,$28,$91
@ref48:
	.byte $93,$f9,$91,$27,$91,$f9,$91,$27,$87,$f9,$87,$28,$87,$f9,$af
@ref49:
	.byte $a7,$28,$91,$f9,$91,$27,$87,$f9,$87,$28,$91,$f9,$91,$28,$91
	.byte $ff,$0f
	.word @ref48
	.byte $ff,$0f
	.word @ref49
	.byte $ff,$0f
	.word @ref48
@ref50:
	.byte $a7,$28,$91,$f9,$91,$27,$87,$f9,$87,$28,$91,$f9,$91,$27,$91
@ref51:
	.byte $f7,$9d,$f9,$87
@ref52:
	.byte $93,$8e,$25,$b9,$28,$91,$25,$91,$2a,$91,$25,$91
@ref53:
	.byte $93,$2c,$a5,$25,$91,$2a,$91,$25,$91,$28,$91,$25,$91
@ref54:
	.byte $93,$20,$b9,$23,$91,$20,$91,$23,$91,$26,$27,$81,$28,$8b
@ref55:
	.byte $27,$91,$25,$f7,$91
@ref56:
	.byte $cf,$28,$91,$25,$91,$2a,$91,$25,$91
@ref57:
	.byte $93,$2a,$2b,$81,$2c,$9f,$25,$91,$2a,$91,$25,$91,$28,$91,$25,$91
@ref58:
	.byte $93,$20,$b9,$23,$91,$25,$91,$26,$27,$81,$28,$8b,$27,$91
@ref59:
	.byte $23,$91,$25,$f7,$91
@ref60:
	.byte $a7,$2a,$81,$2b,$81,$2c,$d9,$2a,$91
@ref61:
	.byte $28,$91,$27,$e1,$28,$9b,$2a,$87
@ref62:
	.byte $95,$2b,$81,$2c,$ef,$82,$27,$91
@ref63:
	.byte $89,$f9,$87,$27,$87,$f9,$87,$2a,$91,$f9,$91,$2c,$9b,$f9,$af
@ref64:
	.byte $a7,$8e,$2a,$81,$2b,$81,$2c,$d9,$2a,$91
	.byte $ff,$08
	.word @ref61
@ref65:
	.byte $93,$25,$f7,$91
@ref66:
	.byte $93,$80,$20,$87,$f9,$87,$20,$87,$f9,$87,$20,$87,$f9,$87,$20,$87,$f9,$c3
@ref67:
	.byte $88,$2c,$c3,$f9,$87,$2a,$c3,$f9,$87
@ref68:
	.byte $28,$af,$f9,$87,$2a,$cd,$f9,$91
@ref69:
	.byte $2c,$c3,$f9,$87,$2a,$c3,$f9,$87
	.byte $ff,$08
	.word @ref68
	.byte $ff,$08
	.word @ref69
	.byte $ff,$08
	.word @ref68
@ref70:
	.byte $2d,$c3,$f9,$87,$2c,$c3,$f9,$87
@ref71:
	.byte $2a,$af,$f9,$87,$2c,$cd,$f9,$91
@ref72:
	.byte $2c,$9b,$f9,$87,$2a,$9b,$f9,$87,$28,$91,$f9,$87,$2a,$91,$f9,$87,$2c,$91
@ref73:
	.byte $9d,$f9,$87,$2a,$9b,$f9,$87,$28,$91,$f9,$87,$2a,$91,$f9,$87,$2c,$91
@ref74:
	.byte $9d,$f9,$87,$2a,$9b,$f9,$87,$28,$91,$f9,$87,$2a,$91,$f9,$87,$28,$91
@ref75:
	.byte $b1,$f9,$87,$27,$c3,$f9,$87,$2c,$91
	.byte $ff,$11
	.word @ref73
	.byte $ff,$11
	.word @ref73
@ref76:
	.byte $9d,$f9,$87,$2a,$9b,$f9,$87,$2c,$91,$f9,$87,$2f,$91,$f9,$87,$31,$91
@ref77:
	.byte $f7,$9d,$f9,$87
@ref78:
	.byte $84,$25,$91,$27,$91,$28,$91,$2a,$91,$25,$91,$27,$91,$28,$91,$2a,$91
@ref79:
	.byte $25,$91,$27,$91,$28,$91,$2a,$91,$25,$91,$27,$91,$28,$91,$2a,$91
	.byte $ff,$10
	.word @ref79
	.byte $ff,$10
	.word @ref79
	.byte $ff,$10
	.word @ref79
@ref80:
	.byte $27,$91,$28,$91,$2a,$91,$2c,$b9,$2f,$91,$31,$91
@ref81:
	.byte $93,$33,$91,$34,$91,$36,$91,$31,$91,$33,$91,$34,$91,$36,$91
@ref82:
	.byte $93,$38,$91,$39,$91,$3b,$91,$36,$91,$38,$91,$39,$91,$3b,$91
@ref83:
	.byte $3d,$cd,$63,.lobyte(@env17),.hibyte(@env17),$cf
@ref84:
	.byte $cd,$63,.lobyte(@env8),.hibyte(@env8),$65,$81,$62,$61,$06,$3d,$30,$cd
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref85:
	.byte $98,$32,$31,$32,$81,$31,$32,$33,$32,$31,$32,$96,$32,$85,$00,$32,$85,$00,$2a,$85,$00,$2a,$85,$00,$26,$8f,$00
@song0ch2loop:
@ref86:
	.byte $96,$28,$83,$00,$8b,$28,$83,$00,$8b,$2e,$8f,$00,$28,$83,$00,$8b,$28,$83,$00,$8b,$28,$83,$00,$8b,$2e,$8f,$00,$28,$83,$00,$8b
@ref87:
	.byte $28,$83,$00,$8b,$28,$83,$00,$8b,$2e,$8f,$00,$28,$83,$00,$8b,$28,$83,$00,$8b,$28,$83,$00,$8b,$2e,$8f,$00,$28,$83,$00,$8b
	.byte $ff,$1e
	.word @ref87
@ref88:
	.byte $32,$8f,$00,$32,$8f,$00,$2a,$8f,$00,$26,$8f,$00,$32,$85,$00,$32,$85,$00,$89,$32,$85,$00,$2a,$85,$00,$2a,$85,$00,$26,$8f,$00
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
@ref89:
	.byte $32,$85,$00,$32,$85,$00,$2a,$85,$00,$26,$85,$00,$32,$85,$00,$2a,$85,$00,$2a,$85,$00,$26,$85,$00,$98,$32,$31,$32,$81,$31,$32,$33,$32,$31,$32,$96,$32,$85,$00,$32,$85,$00,$2a,$85,$00,$2a,$85,$00,$26,$85,$00,$26,$85,$00
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1f
	.word @ref88
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$34
	.word @ref89
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1f
	.word @ref88
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$34
	.word @ref89
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1f
	.word @ref88
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
@ref90:
	.byte $28,$83,$00,$8b,$2e,$8f,$00,$2e,$8f,$00,$2e,$8f,$00,$2e,$8f,$00,$95,$98,$2e,$83,$00,$9d
@ref91:
	.byte $96,$28,$83,$00,$c7,$28,$83,$00,$c7
@ref92:
	.byte $28,$83,$00,$b3,$28,$83,$00,$9f,$98,$2e,$83,$00,$8b,$96,$28,$83,$00,$9f
@ref93:
	.byte $28,$83,$00,$c7,$28,$83,$00,$c7
	.byte $ff,$10
	.word @ref92
	.byte $ff,$08
	.word @ref93
	.byte $ff,$10
	.word @ref92
	.byte $ff,$08
	.word @ref93
@ref94:
	.byte $28,$83,$00,$b3,$28,$83,$00,$9f,$2e,$8f,$00,$2e,$8f,$00,$2e,$8f,$00
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1f
	.word @ref88
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$34
	.word @ref89
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1f
	.word @ref88
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$34
	.word @ref89
	.byte $ff,$1e
	.word @ref87
	.byte $ff,$34
	.word @ref89
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref95:
	.byte $92,$26,$83,$26,$85,$26,$83,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87
@song0ch3loop:
@ref96:
	.byte $90,$1c,$91,$1c,$91,$92,$26,$91,$90,$1c,$91,$1c,$91,$1c,$91,$92,$26,$91,$90,$1c,$91
@ref97:
	.byte $1c,$91,$1c,$91,$92,$26,$91,$90,$1c,$91,$1c,$91,$1c,$91,$92,$26,$91,$90,$1c,$91
	.byte $ff,$10
	.word @ref97
@ref98:
	.byte $94,$26,$91,$26,$91,$26,$91,$26,$91,$26,$87,$26,$91,$26,$87,$26,$87,$26,$87,$26,$91
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
@ref99:
	.byte $94,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87,$26,$87
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$14
	.word @ref98
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$20
	.word @ref99
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$14
	.word @ref98
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$20
	.word @ref99
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$14
	.word @ref98
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
@ref100:
	.byte $1c,$91,$92,$26,$91,$26,$91,$26,$91,$26,$a7,$26,$a3
@ref101:
	.byte $90,$1c,$cd,$1c,$cd
@ref102:
	.byte $1c,$b9,$1c,$a5,$92,$26,$91,$90,$1c,$a5
@ref103:
	.byte $1c,$cd,$1c,$cd
	.byte $ff,$08
	.word @ref102
@ref104:
	.byte $1c,$cd,$1c,$cd
	.byte $ff,$08
	.word @ref102
@ref105:
	.byte $1c,$cd,$1c,$cd
@ref106:
	.byte $1c,$b9,$1c,$a5,$92,$26,$91,$26,$91,$26,$91
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$14
	.word @ref98
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$20
	.word @ref99
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$14
	.word @ref98
	.byte $ff,$10
	.word @ref96
	.byte $ff,$10
	.word @ref97
	.byte $ff,$10
	.word @ref97
	.byte $ff,$20
	.word @ref99
	.byte $ff,$10
	.word @ref96
	.byte $ff,$20
	.word @ref99
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref107:
	.byte $cf
@song0ch4loop:
@ref108:
	.byte $01,$91,$01,$91,$01,$91,$01,$91,$01,$91,$01,$91,$01,$91,$01,$91
@ref109:
	.byte $02,$91,$02,$91,$03,$91,$04,$91,$04,$91,$05,$91,$04,$91,$05,$91
	.byte $ff,$10
	.word @ref108
@ref110:
	.byte $06,$91,$06,$91,$07,$91,$04,$91,$04,$91,$05,$91,$04,$91,$05,$91
	.byte $ff,$10
	.word @ref108
	.byte $ff,$10
	.word @ref109
	.byte $ff,$10
	.word @ref108
	.byte $ff,$10
	.word @ref110
	.byte $ff,$10
	.word @ref108
	.byte $ff,$10
	.word @ref108
	.byte $ff,$10
	.word @ref108
	.byte $ff,$10
	.word @ref108
	.byte $ff,$10
	.word @ref108
	.byte $ff,$10
	.word @ref108
@ref111:
	.byte $01,$91,$01,$91,$01,$91,$01,$91,$01,$91,$01,$91,$01,$91,$02,$91
@ref112:
	.byte $02,$91,$02,$91,$02,$91,$02,$91,$02,$91,$02,$91,$02,$91,$02,$91
@ref113:
	.byte $01,$91,$01,$91,$01,$91,$08,$91,$01,$91,$08,$91,$01,$91,$01,$91
@ref114:
	.byte $09,$91,$0a,$91,$09,$91,$09,$91,$09,$91,$0a,$91,$09,$91,$09,$91
@ref115:
	.byte $02,$91,$02,$91,$02,$91,$03,$91,$09,$91,$0a,$91,$09,$91,$09,$91
@ref116:
	.byte $01,$91,$08,$91,$01,$91,$01,$91,$01,$91,$08,$91,$01,$91,$01,$91
	.byte $ff,$10
	.word @ref113
	.byte $ff,$10
	.word @ref114
	.byte $ff,$10
	.word @ref115
	.byte $ff,$10
	.word @ref116
@ref117:
	.byte $04,$91,$04,$91,$05,$91,$04,$91,$04,$91,$04,$91,$05,$91,$04,$91
@ref118:
	.byte $02,$91,$02,$91,$03,$91,$02,$91,$02,$91,$02,$91,$03,$91,$02,$91
@ref119:
	.byte $01,$91,$01,$91,$08,$91,$01,$91,$08,$91,$01,$91,$01,$91,$08,$91
@ref120:
	.byte $01,$91,$01,$91,$08,$91,$01,$91,$01,$91,$08,$91,$01,$91,$08,$91
	.byte $ff,$10
	.word @ref117
	.byte $ff,$10
	.word @ref118
	.byte $ff,$10
	.word @ref119
@ref121:
	.byte $01,$91,$01,$91,$01,$91,$01,$91,$01,$cd
@ref122:
	.byte $01,$cd,$01,$cd
@ref123:
	.byte $01,$b9,$01,$a5,$01,$91,$08,$91,$01,$91
@ref124:
	.byte $09,$cd,$09,$cd
@ref125:
	.byte $09,$b9,$09,$a5,$09,$91,$0a,$91,$09,$91
@ref126:
	.byte $0b,$cd,$0b,$cd
@ref127:
	.byte $0b,$b9,$0b,$a5,$0b,$91,$0a,$91,$0b,$91
@ref128:
	.byte $09,$cd,$09,$cd
@ref129:
	.byte $09,$b9,$09,$a5,$0a,$91,$09,$91,$0a,$91
	.byte $ff,$10
	.word @ref120
@ref130:
	.byte $09,$91,$09,$91,$0a,$91,$09,$91,$09,$91,$0a,$91,$09,$91,$0a,$91
@ref131:
	.byte $0b,$91,$0b,$91,$0c,$91,$0b,$91,$0b,$91,$0c,$91,$0b,$91,$0c,$91
	.byte $ff,$10
	.word @ref130
	.byte $ff,$10
	.word @ref120
	.byte $ff,$10
	.word @ref130
	.byte $ff,$10
	.word @ref131
	.byte $ff,$10
	.word @ref120
@ref132:
	.byte $01,$91,$01,$91,$01,$91,$08,$91,$01,$91,$01,$91,$0a,$91,$08,$91
@ref133:
	.byte $09,$91,$09,$91,$09,$91,$0a,$91,$09,$91,$09,$91,$0c,$91,$0a,$91
@ref134:
	.byte $0d,$91,$0d,$91,$0d,$91,$0e,$91,$0d,$91,$0d,$91,$02,$91,$0e,$91
@ref135:
	.byte $0b,$91,$0b,$91,$0b,$91,$0c,$91,$0b,$91,$0b,$91,$0f,$91,$0c,$91
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref133
	.byte $ff,$10
	.word @ref134
	.byte $ff,$10
	.word @ref135
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref120
	.byte $fd
	.word @song0ch4loop
