; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_doom_eternal=music_data_doom_eternal
.endif

music_data_doom_eternal:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19
	.byte .lobyte(@tempo_env_9_mid), .hibyte(@tempo_env_9_mid), 0, 0

.export music_data_doom_eternal
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env9,@env1,@env8,@env4
	.word @env3,@env1,@env5,@env4

@instruments_exp:
	.word @env0, @env1, @env4
	.byte $00, $00
	.byte $00, $00, $00, $00, $00, $00, $00, $00
	.word @env6, @env1, @env4
	.byte $00, $00
	.byte $00, $00, $00, $00, $00, $00, $00, $00
	.word @env6, @env1, @env4
	.byte $00, $00
	.byte $00, $00, $00, $00, $00, $00, $00, $00
	.word @env2, @env1, @env4
	.byte $00, $00
	.byte $00, $00, $00, $00, $00, $00, $00, $00
	.word @env7, @env1, @env4
	.byte $00, $00
	.byte $00, $00, $00, $00, $00, $00, $00, $00

@instruments_exp_extra:
	.byte $39,$c0,$06,$23,$1f,$11,$05,$2f,$00,$60,$2c,$1f,$0f,$04,$2f,$00,$30,$17,$5f,$13,$04,$2f,$00,$01,$00,$51,$09,$03,$2f,$00,$00
	.byte $3a,$c0,$34,$19,$17,$03,$00,$17,$00,$51,$0d,$13,$03,$00,$57,$00,$31,$19,$1b,$00,$00,$57,$00,$76,$00,$17,$03,$00,$1f,$00,$00
	.byte $0c,$c0,$12,$1e,$89,$00,$01,$0a,$00,$71,$00,$12,$00,$00,$0a,$00,$72,$12,$4e,$8b,$1d,$8a,$00,$11,$0c,$13,$8f,$06,$2a,$00,$23
	.byte $32,$c0,$31,$1e,$12,$05,$00,$17,$00,$37,$15,$0f,$08,$00,$28,$00,$72,$34,$0a,$09,$03,$29,$00,$02,$00,$9f,$16,$00,$19,$00,$02
	.byte $3c,$c0,$31,$1d,$cb,$0b,$00,$01,$00,$01,$06,$07,$08,$00,$25,$00,$01,$1c,$8b,$8a,$00,$11,$00,$01,$03,$07,$08,$00,$15,$00,$05

@samples:
@env0:
	.byte $04,$ca,$7f,$00,$01
@env1:
	.byte $c0,$7f,$00,$00
@env2:
	.byte $00,$cb,$ca,$00,$02
@env3:
	.byte $04,$cf,$7f,$00,$01
@env4:
	.byte $00,$c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $04,$c8,$7f,$00,$01
@env7:
	.byte $04,$cb,$7f,$00,$01
@env8:
	.byte $c0,$c2,$c1,$c1,$c0,$03,$c0,$00,$00
@env9:
	.byte $00,$c2,$c4,$c6,$00,$03
@tempo_env_9_mid:
	.byte $03,$06,$04,$05,$80
@song0ch0:
@song0ch0loop:
	.byte $6a, .lobyte(@tempo_env_9_mid), .hibyte(@tempo_env_9_mid), $77, $6e, $02, $f0, $80
@song0ref10:
	.byte $10, $8f, $62, $1a, $8f, $62, $1c, $8f, $62, $10, $8f, $62, $17, $8f, $62, $18, $8f, $62, $10, $8f, $62, $15, $8f, $62
	.byte $17, $8f, $62, $10, $8f, $62, $13, $8f, $62, $10, $8f, $62, $17, $8f, $62, $18, $8f, $62, $15, $8f, $62, $17, $8f, $6b
@song0ref58:
	.byte $62, $10, $8f, $62, $1a, $8f, $62, $1c, $8f, $62, $10, $8f, $62, $17, $8f, $62, $18, $8f, $62, $10, $8f, $62, $15, $8f
	.byte $62, $10, $8f, $62, $1d, $8f, $62, $1c, $8f, $62, $10, $8f, $62, $1a, $8f, $62, $1c, $8f, $62, $17, $8f, $62, $1b, $8f
	.byte $6b, $62, $10, $8f, $62, $1a, $8f, $62, $1c, $8f, $62, $10, $8f, $62, $15, $8f, $62, $17, $8f, $62, $13, $8f, $62, $15
	.byte $8f, $62, $10, $8f, $62, $13, $8f, $62, $17, $8f, $62, $10, $8f, $62, $17, $8f, $62, $18, $8f, $62, $13, $8f, $62, $17
	.byte $8f, $6b, $62, $1a, $8f, $62, $1c, $8f, $62, $10, $8f, $62, $18, $8f, $62, $1a, $8f, $62, $10, $8f, $62, $17, $8f, $62
	.byte $10, $8f, $62, $1c, $8f, $62, $1d, $8f, $62, $10, $8f, $62, $1c, $8f, $62, $1e, $8f, $62, $10, $8f, $62, $1b, $8f, $62
	.byte $10, $8f, $6b
	.byte $ff, $80
	.word @song0ref10
	.byte $6b
	.byte $ff, $80
	.word @song0ref10
	.byte $6b, $7c, $6e, $ff, $b0, $62
	.byte $ff, $1f
	.word @song0ref10
	.byte $8d, $81, $6b, $6e, $ff, $90
	.byte $ff, $1f
	.word @song0ref58
	.byte $8d, $81, $6b, $17, $f7, $f7, $ad, $6b, $6e, $ff, $40, $62, $17, $f7, $f7, $ab, $81, $6b, $00, $f7, $f7, $ad, $6b, $f7
	.byte $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $af, $6b, $f7
	.byte $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $af, $6b, $f7
	.byte $f7, $af, $6b, $f7, $f7, $af, $6b, $f7, $f7, $f7, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref316:
	.byte $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $10, $f7, $f7, $ad, $10, $f7, $f7, $ad, $1c, $f7, $f7, $ad, $1c, $f7, $f7, $ad, $10, $f7, $f7, $ad, $10, $f7, $f7
	.byte $ad, $1c, $f7, $f7, $ad, $1c, $f7, $f7, $ad, $10, $f7, $f7, $ad, $10, $f7, $f7, $ad, $1c, $f7, $f7, $ad, $1c, $f7, $f7
	.byte $ad, $1c, $f7, $f7, $ad, $1c, $f7, $f7, $ad, $61, $18, $1c, $07, $f7, $f7, $ad, $00, $f7, $f7, $ad
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $8b, $71, $6e, $0e, $f0, $82, $2c, $9f, $81, $00, $f7, $f7, $ad
	.byte $ff, $18
	.word @song0ref316
	.byte $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $f7, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch6loop
@song0ch7:
@song0ch7loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch7loop
@song0ch8:
@song0ch8loop:
	.byte $70, $6e, $0e, $f0, $82, $1c, $a1, $a3, $1c, $b3, $7c, $62, $1c, $f7, $a7
@song0ref563:
	.byte $62, $1c, $f7, $f7, $ad, $62, $1c, $f7, $f7, $ad, $62, $1c, $f7, $f7, $ad, $62, $1c, $f7, $f7, $ad, $62, $1c, $f7, $f7
	.byte $ad, $62, $1c, $f7, $f7, $ad
	.byte $ff, $18
	.word @song0ref563
	.byte $62, $1c, $f7, $f7, $ad, $62, $1c, $f7, $f7, $ad, $6e, $ff, $40, $62, $1c, $f7, $f7, $ab, $81, $7f, $1c, $c5, $1c, $b3
	.byte $00, $f7, $a7, $7a, $84
@song0ref625:
	.byte $2f, $f7, $f7, $ad, $2f, $f7, $f7, $ad, $2f, $f7, $f7, $ad, $2f, $f7, $f7, $ad, $2f, $f7, $f7, $ad, $2f, $f7, $f7, $ad
	.byte $ff, $18
	.word @song0ref625
	.byte $2f, $f7, $f7, $ad, $2f, $f7, $f7, $ad, $2f, $f7, $f7, $f5, $fd
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
	.byte $77, $6e, $02, $f0, $86
@song0ref673:
	.byte $28, $8f, $62, $32, $8f, $62, $34, $8f, $62, $28, $8f, $62, $2f, $8f, $62, $30, $8f, $62, $28, $8f, $62, $2d, $8f, $62
	.byte $2f, $8f, $62, $28, $8f, $62, $2b, $8f, $62, $28, $8f, $62, $2f, $8f, $62, $30, $8f, $62, $2d, $8f, $62, $2f, $8f
@song0ref720:
	.byte $62, $28, $8f, $62, $32, $8f, $62, $34, $8f, $62, $28, $8f, $62, $2f, $8f, $62, $30, $8f, $62, $28, $8f, $62, $2d, $8f
	.byte $62, $28, $8f, $62, $35, $8f, $62, $34, $8f, $62, $28, $8f, $62, $32, $8f, $62, $34, $8f, $62, $2f, $8f, $62, $33, $8f
@song0ref768:
	.byte $62, $28, $8f, $62, $32, $8f, $62, $34, $8f, $62, $28, $8f, $62, $2d, $8f, $62, $2f, $8f, $62, $2b, $8f, $62, $2d, $8f
	.byte $62, $28, $8f, $62, $2b, $8f, $62, $2f, $8f, $62, $28, $8f, $62, $2f, $8f, $62, $30, $8f, $62, $2b, $8f, $62, $2f, $8f
@song0ref816:
	.byte $62, $32, $8f, $62, $34, $8f, $62, $28, $8f, $62, $30, $8f, $62, $32, $8f, $62, $28, $8f, $62, $2f, $8f, $62, $28, $8f
	.byte $62, $34, $8f, $62, $35, $8f, $62, $28, $8f, $62, $34, $8f, $62, $36, $8f, $62, $28, $8f, $62, $33, $8f, $62, $28, $8f
	.byte $62
	.byte $ff, $80
	.word @song0ref673
	.byte $62
	.byte $ff, $40
	.word @song0ref673
	.byte $6e, $ff, $d0
	.byte $ff, $1f
	.word @song0ref768
	.byte $8d, $81, $6e, $ff, $c0
	.byte $ff, $1f
	.word @song0ref816
	.byte $8d, $81, $6e, $ff, $b0, $62
	.byte $ff, $1f
	.word @song0ref673
	.byte $8d, $81, $6e, $ff, $90
	.byte $ff, $1f
	.word @song0ref720
	.byte $8d, $81, $73, $6e, $01, $50, $88, $1f, $f7, $95, $6e, $01, $90, $f7, $95, $81, $6e, $ff, $60, $62, $1f, $f7, $f7, $ab
	.byte $81, $82, $34, $7f
@song0ref931:
	.byte $8f, $2b, $8f, $23, $8f, $1c, $8f, $3c, $8f, $34, $8f, $28, $8f, $23, $8f, $1c, $8f, $37, $8f, $39, $8f, $28, $8f, $1f
	.byte $8f, $1c, $8f, $62, $37, $8f, $62, $36, $8f, $34
	.byte $ff, $20
	.word @song0ref931
	.byte $ff, $20
	.word @song0ref931
	.byte $ff, $20
	.word @song0ref931
	.byte $ff, $20
	.word @song0ref931
	.byte $ff, $20
	.word @song0ref931
	.byte $ff, $20
	.word @song0ref931
	.byte $ff, $1f
	.word @song0ref931
@song0ref986:
	.byte $62, $34, $8f, $62, $2b, $8f, $62, $23, $8f, $62, $1c, $8f, $62, $3c, $8f, $62, $34, $8f, $62, $28, $8f, $62, $23, $8f
	.byte $62, $1c, $8f, $62, $37, $8f, $62, $39, $8f, $62, $28, $8f, $62, $1f, $8f, $62, $1c, $8f, $62, $37, $8f, $62, $36, $8f
	.byte $ff, $20
	.word @song0ref986
	.byte $ff, $20
	.word @song0ref986
	.byte $ff, $20
	.word @song0ref986
	.byte $ff, $20
	.word @song0ref986
	.byte $6e, $ff, $e0
	.byte $ff, $1f
	.word @song0ref986
	.byte $8d, $81, $6e, $ff, $c0
	.byte $ff, $1f
	.word @song0ref986
	.byte $8d, $81, $6e, $ff, $60
	.byte $ff, $1f
	.word @song0ref986
	.byte $8d, $74, $81, $00, $c5, $fd
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $70, $6e, $0b, $c0, $84, $58, $a1, $f7, $f7, $8b, $62, $58, $f7, $dd, $62, $61, $f7, $58, $56, $c5, $62, $56, $f7, $f7
	.byte $ad, $62, $56, $f7, $f7, $ad, $62, $54, $f7, $f7, $ad, $62, $54, $f7, $dd, $62, $61, $f8, $54, $52, $c5, $62, $61, $ff
	.byte $52, $51, $f7, $f7, $ad, $62, $51, $f7, $f7, $ad, $4c, $f7, $f7, $ad, $62, $4c, $f7, $dd, $62, $61, $fd, $4c, $4b, $c5
	.byte $62, $4a, $f7, $f7, $ad, $62, $4a, $f7, $f7, $ad, $62, $47, $f7, $f7, $ad, $62, $47, $f7, $f7, $ad, $6e, $ff, $a0, $62
	.byte $45, $f7, $f7, $ab, $81, $6e, $ff, $60, $62, $45, $f7, $f7, $ab, $81, $79, $88
@song0ref1189:
	.byte $34, $f7, $f7, $ad, $62, $34, $f7, $f7, $ad, $62, $34, $f7, $f7, $ad, $62, $34, $f7, $f7, $ad, $62, $34, $f7, $f7, $ad
	.byte $62, $34, $f7, $f7, $ad, $62
	.byte $ff, $18
	.word @song0ref1189
	.byte $62, $34, $f7, $f7, $ad, $62, $34, $f7, $f7, $ad, $76, $62, $34, $f7, $f7, $ad, $62, $34, $f7, $f7, $f5, $fd
	.word @song0ch10loop
@song0ch11:
@song0ch11loop:
	.byte $72, $6e, $01, $50, $82
@song0ref1252:
	.byte $1c, $8f, $00, $a1, $1c, $8f, $00, $a1, $1c, $8f, $00, $8f, $1c, $8f, $00, $a1, $1c, $8f, $00, $a1, $1c, $8f, $00, $8d
	.byte $81, $6e, $01, $90
	.byte $ff, $18
	.word @song0ref1252
	.byte $7b, $81
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f, $88, $28, $74, $f7, $f7, $ad, $62, $28, $f7, $f7, $ad, $6e, $01, $a0, $2d, $f7, $f7, $ab, $81, $62, $2d, $f7, $f7
	.byte $ad, $28, $f7, $f7, $ad, $62, $28, $f7, $f7, $ad, $62, $28, $f7, $f7, $ad, $6e, $ff, $80, $62, $28, $f7, $f7, $ab, $81
	.byte $62, $40, $f7, $f7, $ad, $62, $40
@song0ref1363:
	.byte $f7, $f7, $ad, $62, $3b, $f7, $f7, $ad, $62, $3b, $f7, $f7, $ad, $62, $3b, $f7, $f7, $ad, $62, $3b, $f7, $f7, $ad, $62
	.byte $3b, $f7, $f7, $ad, $62, $3b
	.byte $ff, $18
	.word @song0ref1363
	.byte $f7, $f7, $ad, $62, $3b, $f7, $f7, $ad, $62, $3b, $f7, $f7, $f5, $fd
	.word @song0ch11loop
@song0ch12:
@song0ch12loop:
	.byte $70, $6e, $01, $50, $80
	.byte $ff, $19
	.word @song0ref1252
	.byte $6e, $01, $a0
	.byte $ff, $18
	.word @song0ref1252
	.byte $7b, $81
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f
	.byte $ff, $17
	.word @song0ref1252
	.byte $8f, $6e, $ff, $30
	.byte $ff, $19
	.word @song0ref1252
	.byte $6e, $01, $b0, $88, $28, $f7, $f7, $ab, $81, $62, $28, $f7, $f7, $ad, $62, $28, $f7, $f7, $ad, $62, $28, $f7, $f7, $ad
	.byte $62, $28, $f7, $f7, $ad, $6e, $ff, $70, $62, $28, $f7, $f7, $ab, $81
@song0ref1501:
	.byte $62, $39, $f7, $f7, $ad, $62, $39, $f7, $f7, $ad, $62, $39, $f7, $f7, $ad, $62, $39, $f7, $f7, $ad, $62, $39, $f7, $f7
	.byte $ad, $62, $39, $f7, $f7, $ad
	.byte $ff, $18
	.word @song0ref1501
	.byte $62, $39, $f7, $f7, $ad, $62, $39, $f7, $f7, $ad, $62, $39, $f7, $f7, $ad, $62, $39, $f7, $f7, $f5, $fd
	.word @song0ch12loop
@song0ch13:
@song0ch13loop:
	.byte $70, $6e, $0b, $c0, $84, $53, $a1, $f7, $f7, $8b, $62, $53, $f7, $dd, $62, $61, $f9, $53, $51, $c5, $62, $51, $f7, $f7
	.byte $ad, $62, $51, $f7, $f7, $ad, $62, $4f, $f7, $f7, $ad, $62, $4f, $f7, $dd, $62, $61, $fa, $4f, $4d, $c5, $62, $61, $ff
	.byte $4d, $4c, $f7, $f7, $ad, $62, $4c, $f7, $f7, $ad, $47, $f7, $f7, $ad, $62, $47, $f7, $dd, $62, $61, $fe, $47, $46, $c5
	.byte $62, $45, $f7, $f7, $ad, $62, $45, $f7, $f7, $ad, $88, $2b, $77, $f7, $f7, $ad, $62, $2b, $f7, $f7, $ad, $62, $2b, $f7
	.byte $f7, $ad, $00, $f7, $dd, $7f, $a3, $82, $61, $02, $01, $10, $a1, $10, $c5, $10, $b3, $84, $10, $8f, $00, $f7, $95, $7a
	.byte $62
	.byte $ff, $18
	.word @song0ref1189
	.byte $62
	.byte $ff, $18
	.word @song0ref1189
	.byte $62, $34, $f7, $f7, $ad, $62, $34, $f7, $f7, $ad, $62, $34, $f7, $f7, $f5, $fd
	.word @song0ch13loop
@song0ch14:
@song0ch14loop:
	.byte $82, $28, $8f, $00, $b3, $28, $8f, $00, $f7, $cb
	.byte $ff, $18
	.word @song0ref316
	.byte $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $28, $8f, $00
	.byte $b3, $28, $8f, $00, $f7, $cb
	.byte $ff, $18
	.word @song0ref316
	.byte $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $e5, $84, $29, $83
	.byte $00, $29, $87, $fd
	.word @song0ch14loop
@song0ch15:
@song0ch15loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch15loop
@song0ch16:
@song0ch16loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch16loop
@song0ch17:
@song0ch17loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch17loop
@song0ch18:
@song0ch18loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch18loop
@song0ch19:
@song0ch19loop:
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $18
	.word @song0ref316
	.byte $ff, $17
	.word @song0ref316
	.byte $f7, $fd
	.word @song0ch19loop
