;this file for FamiTone2 library generated by FamiStudio

castlevania_2_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env7), .hibyte(@tempo_env7), 0, 0

@instruments:
	.word @env10,@env1,@env1,@env22
	.word @env15,@env18,@env1,@env22
	.word @env17,@env0,@env1,@env22
	.word @env33,@env1,@env1,@env24
	.word @env9,@env1,@env14,@env23
	.word @env31,@env1,@env14,@env23
	.word @env8,@env1,@env1,@env22
	.word @env34,@env1,@env1,@env22
	.word @env4,@env1,@env1,@env22
	.word @env11,@env1,@env1,@env22
	.word @env2,@env1,@env1,@env20
	.word @env28,@env1,@env12,@env22
	.word @env27,@env1,@env1,@env22
	.word @env19,@env1,@env1,@env22
	.word @env3,@env1,@env14,@env22
	.word @env7,@env1,@env14,@env22
	.word @env7,@env1,@env14,@env16
	.word @env32,@env26,@env12,@env22
	.word @env37,@env26,@env1,@env22
	.word @env33,@env1,@env1,@env21
	.word @env9,@env1,@env14,@env36
	.word @env8,@env1,@env1,@env30
	.word @env34,@env1,@env1,@env30
	.word @env35,@env1,@env1,@env30
	.word @env11,@env1,@env1,@env30
	.word @env2,@env1,@env1,@env13
	.word @env32,@env1,@env14,@env30
	.word @env19,@env1,@env1,@env30
	.word @env32,@env1,@env14,@env30
	.word @env25,@env1,@env14,@env5
	.word @env6,@env1,@env1,@env30
	.word @env29,@env1,@env14,@env30

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;1 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;2 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;3 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;4 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;5 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;6 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;7 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;8 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;9 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;10 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;11 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;12 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;13 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;14 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;15 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;16 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;17 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;18 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;19 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;20 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;21 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;22 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;23 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;24 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0b,$0f	;25 (ripped00)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;26 
	.byte $03+.lobyte(FAMISTUDIO_DPCM_PTR),$17,$0e	;27 (ripped01)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;28 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;29 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;30 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;31 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;32 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;33 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;34 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;35 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;36 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;37 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;38 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;39 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;40 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;41 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;42 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;43 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;44 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;45 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;46 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;47 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;48 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;49 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;50 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;51 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;52 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;53 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;54 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;55 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;56 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;57 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;58 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;59 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;60 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;61 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;62 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00	;63 

@env0:
	.byte $c0,$cb,$cc,$cf,$00,$03
@env1:
	.byte $c0,$7f,$00,$00
@env2:
	.byte $00,$c6,$c8,$c7,$c6,$c5,$02,$c3,$03,$c4,$03,$c5,$03,$c6,$06,$c1,$00,$0f
@env3:
	.byte $00,$c5,$03,$c4,$03,$c2,$02,$c2,$00,$07
@env4:
	.byte $00,$c6,$c5,$c5,$c4,$c4,$c3,$00,$06
@env5:
	.byte $00,$c1,$0f,$c1,$c2,$c2,$c1,$bf,$bf,$c0,$00,$03
@env6:
	.byte $00,$c5,$c4,$c3,$03,$c2,$00,$05
@env7:
	.byte $00,$c6,$c5,$03,$c4,$03,$c1,$00,$06
@env8:
	.byte $00,$c7,$c8,$c7,$c6,$c5,$c5,$c2,$c4,$c5,$c4,$c3,$c2,$03,$c3,$c2,$c1,$02,$c2,$00,$12
@env9:
	.byte $00,$c2,$03,$c3,$03,$c4,$03,$c5,$c5,$c6,$c6,$c5,$c5,$c4,$c4,$c4,$00,$0f
@env10:
	.byte $00,$cf,$7d,$cf,$00,$03
@env11:
	.byte $00,$c7,$c9,$c8,$c7,$c6,$c6,$c2,$c4,$c6,$c5,$c4,$c3,$c3,$c2,$00,$0e
@env12:
	.byte $c2,$00,$00
@env13:
	.byte $00,$c1,$0d,$c1,$c2,$c2,$c1,$c0,$c0,$c1,$00,$03
@env14:
	.byte $c1,$00,$00
@env15:
	.byte $00,$c0,$ce,$c8,$c3,$c4,$c3,$c1,$02,$c0,$00,$09
@env16:
	.byte $00,$c0,$c0,$c1,$c1,$c0,$c0,$bf,$bf,$00,$01
@env17:
	.byte $00,$c0,$c6,$c2,$c3,$c1,$c0,$00,$06
@env18:
	.byte $c0,$c2,$ca,$cc,$cd,$cc,$cd,$ce,$d0,$00,$08
@env19:
	.byte $00,$c7,$c6,$c6,$c5,$06,$c2,$00,$06
@env20:
	.byte $00,$c0,$0d,$c0,$c1,$c1,$c0,$bf,$bf,$c0,$00,$03
@env21:
	.byte $00,$c1,$c2,$c2,$c1,$c0,$c0,$c1,$00,$01
@env22:
	.byte $00,$c0,$7f,$00,$01
@env23:
	.byte $00,$c0,$0c,$c0,$c0,$c1,$c1,$c0,$c0,$bf,$bf,$00,$03
@env24:
	.byte $00,$c0,$c1,$c1,$c0,$bf,$bf,$c0,$00,$01
@env25:
	.byte $00,$c5,$03,$c4,$0e,$c3,$04,$c1,$00,$07
@env26:
	.byte $c0,$cc,$00,$01
@env27:
	.byte $00,$c4,$00,$01
@env28:
	.byte $00,$c7,$00,$01
@env29:
	.byte $00,$c6,$00,$01
@env30:
	.byte $00,$c1,$00,$01
@env31:
	.byte $00,$c4,$c5,$03,$c4,$02,$c4,$00,$06
@env32:
	.byte $00,$c8,$00,$01
@env33:
	.byte $00,$c3,$c2,$c1,$00,$03
@env34:
	.byte $00,$c6,$c7,$c6,$c5,$c4,$02,$c3,$c4,$c5,$c6,$c6,$c7,$03,$c2,$00,$0e
@env35:
	.byte $00,$c7,$c6,$c6,$c5,$c5,$c4,$00,$06
@env36:
	.byte $00,$c1,$0c,$c1,$c1,$c2,$c2,$c1,$c1,$c0,$c0,$00,$03
@env37:
	.byte $00,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$00,$07
@tempo_env7:
	.byte $01,$06,$06,$06,$06,$06,$03,$02,$80

@song0ch0:
@ref0:
	.byte $a4,$23,$8b,$1e,$8b,$2a,$8b,$1e,$8b,$28,$8b,$1e,$8b,$26,$8b,$1e,$8b,$25,$8b,$1e,$8b,$26,$8b,$1e,$8b,$25,$8b,$1e,$8b,$23,$8b,$1e,$8b
@ref1:
	.byte $25,$8b,$1e,$8b,$26,$8b,$1e,$8b,$28,$8b,$1e,$8b,$26,$8b,$1e,$8b,$25,$8b,$1e,$8b,$21,$8b,$1e,$8b,$25,$8b,$1e,$8b,$23,$8b,$1e,$8b
@ref2:
	.byte $23,$8b,$1e,$8b,$2a,$8b,$1e,$8b,$28,$8b,$1e,$8b,$26,$8b,$1e,$8b,$25,$8b,$1e,$8b,$26,$8b,$1e,$8b,$25,$8b,$1e,$8b,$23,$8b,$1e,$8b
	.byte $ff,$20
	.word @ref1
@song0ch0loop:
@ref3:
	.byte $fb,.lobyte(@tempo_env7),.hibyte(@tempo_env7),$98,$31,$9c,$31,$97,$98,$34,$9c,$34,$89,$98,$32,$9c,$32,$97,$a2,$19,$81,$9e,$25,$87,$a2,$17,$81,$9e,$23,$87,$a2,$19,$81,$9e,$25,$87,$a2,$1a,$81,$9e,$26,$95,$a2,$1c,$81,$9e,$28,$95,$a2,$2a,$9e,$2a,$b3
@ref4:
	.byte $98,$31,$9e,$31,$a5,$98,$36,$9e,$36,$a5,$98,$32,$a0,$32,$cf,$98,$31,$9e,$31,$97,$98,$2f,$9e,$2f,$97
@ref5:
	.byte $98,$31,$9c,$31,$97,$98,$34,$9c,$34,$89,$98,$32,$9c,$32,$97,$a2,$1c,$9e,$28,$89,$a2,$1a,$9e,$26,$89,$a2,$1c,$9e,$28,$89,$a2,$1e,$9e,$2a,$97,$a2,$1f,$9e,$2b,$97,$a2,$21,$9e,$2d,$97,$a2,$23,$9e,$2f,$97
@ref6:
	.byte $88,$31,$99,$86,$31,$8b,$88,$31,$a7,$86,$31,$99,$88,$2f,$99,$86,$2f,$8b,$88,$2f,$a7,$86,$2f,$99
@ref7:
	.byte $98,$31,$9c,$31,$97,$98,$34,$9c,$34,$89,$98,$32,$9c,$32,$97,$a2,$19,$81,$9e,$25,$87,$a2,$17,$81,$9e,$23,$87,$a2,$19,$81,$9e,$25,$87,$a2,$1a,$81,$9e,$26,$95,$a2,$1c,$81,$9e,$28,$95,$a2,$2a,$9e,$2a,$b3
	.byte $ff,$0f
	.word @ref4
	.byte $ff,$1e
	.word @ref5
@ref8:
	.byte $88,$31,$99,$86,$31,$8b,$88,$31,$a7,$86,$31,$99,$8a,$2e,$8f,$86,$2e,$87,$8a,$2f,$8f,$86,$2f,$87,$8a,$31,$8f,$86,$31,$87,$8a,$34,$8f,$86,$34,$87
@ref9:
	.byte $8c,$28,$a7,$8e,$26,$a7,$32,$99,$8c,$28,$a7,$8e,$26,$a7,$32,$99
@ref10:
	.byte $8c,$28,$a7,$26,$a7,$32,$99,$96,$26,$90,$26,$89,$96,$32,$90,$32,$89,$96,$25,$90,$25,$89,$96,$31,$90,$31,$89,$96,$23,$90,$23,$89,$96,$2f,$90,$2f,$89,$96,$21,$90,$21,$89,$96,$2d,$90,$2d,$89
@ref11:
	.byte $92,$28,$99,$26,$8b,$94,$32,$c3,$92,$28,$99,$26,$8b,$94,$32,$c3
@ref12:
	.byte $92,$28,$99,$26,$8b,$94,$32,$c3,$a2,$32,$9a,$32,$97,$a2,$34,$9a,$34,$97,$a2,$31,$9a,$31,$89,$a2,$32,$9a,$32,$a5
	.byte $ff,$20
	.word @ref0
	.byte $ff,$20
	.word @ref1
	.byte $ff,$20
	.word @ref2
	.byte $ff,$20
	.word @ref1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref13:
	.byte $be,$3b,$bc,$3b,$89,$be,$36,$bc,$36,$89,$be,$42,$bc,$42,$89,$be,$36,$bc,$36,$89,$be,$40,$bc,$40,$89,$be,$36,$bc,$36,$89,$be,$3e,$bc,$3e,$89,$be,$36,$bc,$36,$89,$be,$3d,$bc,$3d,$89,$be,$36,$bc,$36,$89,$be,$3e,$bc,$3e,$89,$be,$36,$bc,$36,$89,$be,$3d,$bc,$3d,$89,$be,$36,$bc,$36,$89,$be,$3b,$bc,$3b,$89,$be,$36,$bc,$36,$89
@ref14:
	.byte $be,$3d,$bc,$3d,$89,$be,$36,$bc,$36,$89,$be,$3e,$bc,$3e,$89,$be,$36,$bc,$36,$89,$be,$40,$bc,$40,$89,$be,$36,$bc,$36,$89,$be,$3e,$bc,$3e,$89,$be,$36,$bc,$36,$89,$be,$3d,$bc,$3d,$89,$be,$36,$bc,$36,$89,$be,$39,$bc,$39,$89,$be,$36,$bc,$36,$89,$be,$3d,$bc,$3d,$89,$be,$36,$bc,$36,$89,$be,$3b,$bc,$3b,$89,$be,$36,$bc,$36,$89
	.byte $ff,$30
	.word @ref13
	.byte $ff,$30
	.word @ref14
@song0ch1loop:
@ref15:
	.byte $98,$34,$9c,$34,$97,$98,$39,$9c,$39,$89,$98,$36,$ba,$36,$f7,$81,$98,$34,$9c,$34,$97,$98,$32,$9c,$32,$97
@ref16:
	.byte $98,$34,$ba,$34,$a5,$98,$39,$ba,$39,$a5,$98,$36,$ba,$36,$cf,$98,$34,$9c,$34,$97,$98,$32,$9c,$32,$97
@ref17:
	.byte $98,$34,$9c,$34,$97,$98,$39,$9c,$39,$89,$80,$36,$ba,$36,$f7,$81,$98,$34,$9c,$34,$97,$98,$36,$9c,$36,$97
@ref18:
	.byte $a8,$37,$99,$a6,$37,$8b,$a8,$39,$a7,$a6,$39,$99,$a8,$36,$99,$a6,$36,$8b,$a8,$37,$a7,$a6,$37,$99
	.byte $ff,$10
	.word @ref15
	.byte $ff,$0f
	.word @ref16
@ref19:
	.byte $98,$34,$9c,$34,$97,$98,$39,$9c,$39,$89,$98,$36,$ba,$36,$f7,$81,$98,$34,$9c,$34,$97,$98,$36,$9c,$36,$97
@ref20:
	.byte $a8,$37,$99,$a6,$37,$8b,$a8,$39,$a7,$a6,$39,$99,$8a,$36,$8f,$86,$36,$87,$8a,$38,$8f,$86,$38,$87,$8a,$3a,$8f,$86,$3a,$87,$8a,$3d,$8f,$86,$3d,$87
@ref21:
	.byte $aa,$31,$a7,$ac,$2f,$a7,$3b,$99,$aa,$31,$a7,$ac,$2f,$a7,$3b,$99
@ref22:
	.byte $aa,$31,$a7,$2f,$a7,$3b,$99,$b4,$32,$ae,$32,$89,$b4,$3e,$ae,$3e,$89,$b4,$31,$ae,$31,$89,$b4,$3d,$ae,$3d,$89,$b4,$2f,$ae,$2f,$89,$b4,$3b,$ae,$3b,$89,$b4,$2d,$ae,$2d,$89,$b4,$39,$ae,$39,$89
@ref23:
	.byte $b0,$31,$8b,$31,$8b,$2f,$8b,$b2,$3b,$c3,$b0,$31,$8b,$31,$8b,$2f,$8b,$b2,$3b,$c3
@ref24:
	.byte $b0,$31,$8b,$31,$8b,$2f,$8b,$b2,$3b,$c3,$b8,$3e,$b6,$3e,$97,$b8,$40,$b6,$40,$97,$b8,$3d,$b6,$3d,$89,$b8,$3e,$b6,$3e,$a5
	.byte $ff,$30
	.word @ref13
	.byte $ff,$30
	.word @ref14
	.byte $ff,$30
	.word @ref13
	.byte $ff,$30
	.word @ref14
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref25:
	.byte $80,$23,$f7,$e5
@ref26:
	.byte $1e,$ed,$2a,$ed
@ref27:
	.byte $23,$f7,$e5
@ref28:
	.byte $1e,$ed,$2a,$ed
@song0ch2loop:
@ref29:
	.byte $80,$23,$97,$00,$2f,$89,$00,$23,$8b,$00,$8b,$23,$8b,$2f,$89,$00,$8d,$23,$97,$00,$2f,$89,$00,$8d,$23,$89,$00,$8d,$2f,$89,$00,$8d
@ref30:
	.byte $21,$97,$00,$2d,$89,$00,$21,$89,$00,$8d,$21,$89,$00,$2d,$8b,$00,$8b,$21,$89,$00,$8d,$2d,$89,$00,$8d,$21,$89,$00,$21,$89,$00,$2d,$8b,$00,$8b
@ref31:
	.byte $1f,$97,$00,$2b,$89,$00,$1f,$89,$00,$8d,$1f,$89,$00,$2b,$89,$00,$8d,$1f,$89,$00,$1f,$89,$00,$2b,$89,$00,$8d,$1f,$8b,$00,$8b,$2b,$89,$00,$8d
@ref32:
	.byte $1e,$89,$00,$1e,$89,$00,$2a,$89,$00,$1e,$89,$00,$8d,$1e,$89,$00,$2a,$89,$00,$8d,$1e,$89,$00,$8d,$2a,$89,$00,$8d,$1e,$89,$00,$1e,$89,$00,$2a,$89,$00,$8d
@ref33:
	.byte $23,$97,$00,$2f,$8b,$23,$89,$00,$8d,$23,$8b,$2f,$89,$00,$8d,$23,$89,$00,$23,$89,$00,$2f,$8b,$00,$8b,$23,$8b,$00,$8b,$2f,$89,$00,$8d
@ref34:
	.byte $21,$97,$00,$2d,$89,$00,$21,$89,$00,$8d,$21,$89,$00,$2d,$89,$00,$8d,$21,$8b,$00,$8b,$2d,$89,$00,$8d,$21,$89,$00,$21,$89,$00,$2d,$89,$00,$8d
@ref35:
	.byte $1f,$97,$00,$2b,$8b,$1f,$89,$00,$8d,$1f,$89,$00,$2b,$89,$00,$8d,$1f,$89,$00,$1f,$89,$00,$2b,$89,$00,$8d,$1f,$89,$00,$8d,$2b,$8b,$00,$8b
@ref36:
	.byte $1e,$89,$00,$1e,$89,$00,$2a,$89,$00,$1e,$8b,$00,$8b,$1e,$89,$00,$2a,$89,$00,$8d,$1e,$8b,$2a,$89,$00,$20,$89,$00,$2c,$89,$00,$22,$89,$00,$2e,$89,$00,$25,$89,$00,$31,$89,$00
@ref37:
	.byte $23,$a5,$00,$23,$a5,$00,$23,$89,$00,$2f,$8b,$21,$a5,$00,$21,$a5,$00,$21,$8b,$2d,$89,$00
@ref38:
	.byte $1f,$a5,$00,$1f,$a5,$00,$1f,$89,$00,$2b,$89,$00,$21,$a5,$00,$21,$a5,$00,$21,$89,$00,$2d,$8b
@ref39:
	.byte $23,$a5,$00,$23,$a5,$00,$23,$89,$00,$2f,$89,$00,$21,$a5,$00,$21,$a5,$00,$21,$97,$00
@ref40:
	.byte $1f,$a5,$00,$1f,$a5,$00,$1f,$89,$00,$2b,$89,$00,$21,$97,$00,$2d,$97,$00,$21,$89,$00,$21,$89,$00,$2d,$97,$00
@ref41:
	.byte $23,$f7,$e5
@ref42:
	.byte $1e,$ed,$2a,$ed
@ref43:
	.byte $23,$f7,$e5
@ref44:
	.byte $1e,$ed,$2a,$ed
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref45:
	.byte $f7,$e7
@ref46:
	.byte $f7,$af,$82,$1f,$b5
@ref47:
	.byte $f7,$e7
@ref48:
	.byte $f7,$af,$1f,$99,$1f,$8b,$1f,$8b
@song0ch3loop:
@ref49:
	.byte $9b,$82,$1f,$b5,$1f,$b5,$1f,$b5,$1f,$99
@ref50:
	.byte $9b,$1f,$b5,$1f,$b5,$1f,$b5,$1f,$8b,$1f,$8b
@ref51:
	.byte $9b,$1f,$b5,$1f,$b5,$1f,$b5,$1f,$99
	.byte $ff,$0b
	.word @ref50
	.byte $ff,$09
	.word @ref51
	.byte $ff,$0b
	.word @ref50
	.byte $ff,$09
	.word @ref51
@ref52:
	.byte $9b,$1f,$b5,$1f,$8b,$1f,$b5,$1f,$99,$1f,$8b,$1f,$8b,$1f,$8b
	.byte $ff,$0b
	.word @ref50
	.byte $ff,$0b
	.word @ref50
	.byte $ff,$0b
	.word @ref50
@ref53:
	.byte $9b,$1f,$b5,$1f,$b5,$1f,$8b,$1f,$99,$1f,$8b,$1f,$8b,$1f,$8b
@ref54:
	.byte $9b,$84,$1f,$8b,$1f,$a7,$1f,$8b,$1f,$8b,$1f,$99,$1f,$8b,$1f,$a7,$1f,$8b,$1f,$8b
@ref55:
	.byte $1f,$99,$1f,$8b,$1f,$a7,$1f,$8b,$1f,$8b,$1f,$99,$1f,$8b,$1f,$a7,$82,$1f,$99
	.byte $ff,$13
	.word @ref54
@ref56:
	.byte $1f,$99,$1f,$8b,$1f,$a7,$1f,$8b,$1f,$8b,$1f,$b5,$82,$1f,$99,$1f,$8b,$1f,$8b
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref57:
	.byte $19,$f7,$e5
@ref58:
	.byte $19,$ed,$19,$b5,$1b,$b5
@ref59:
	.byte $19,$f7,$e5
@ref60:
	.byte $19,$ed,$19,$b5,$1b,$99,$1b,$8b,$1b,$8b
@song0ch4loop:
@ref61:
	.byte $19,$99,$1b,$8b,$19,$99,$19,$8b,$1b,$99,$19,$99,$1b,$99,$19,$8b,$19,$8b,$1b,$99
@ref62:
	.byte $19,$99,$1b,$8b,$19,$99,$19,$8b,$1b,$99,$19,$99,$1b,$99,$19,$8b,$19,$8b,$1b,$8b,$1b,$8b
	.byte $ff,$14
	.word @ref61
	.byte $ff,$16
	.word @ref62
	.byte $ff,$14
	.word @ref61
@ref63:
	.byte $19,$99,$1b,$8b,$19,$99,$19,$8b,$1b,$99,$19,$99,$1b,$99,$19,$99,$1b,$8b,$1b,$8b
	.byte $ff,$14
	.word @ref61
@ref64:
	.byte $19,$99,$1b,$8b,$19,$99,$19,$8b,$1b,$8b,$1b,$8b,$19,$99,$19,$8b,$1b,$8b,$19,$8b,$1b,$8b,$1b,$8b,$1b,$8b
@ref65:
	.byte $19,$99,$1b,$8b,$19,$99,$19,$8b,$1b,$99,$19,$99,$1b,$8b,$19,$99,$19,$8b,$1b,$8b,$1b,$8b
	.byte $ff,$16
	.word @ref65
	.byte $ff,$16
	.word @ref65
@ref66:
	.byte $19,$99,$1b,$8b,$19,$99,$19,$8b,$1b,$8b,$19,$99,$19,$8b,$1b,$8b,$1b,$8b,$19,$8b,$1b,$8b,$1b,$8b,$1b,$8b
@ref67:
	.byte $19,$b5,$19,$ed,$19,$b5
@ref68:
	.byte $b7,$19,$ed,$19,$99,$1b,$99
	.byte $ff,$06
	.word @ref67
@ref69:
	.byte $b7,$19,$d1,$19,$8b,$19,$8b,$1b,$99,$1b,$8b,$1b,$8b
	.byte $fd
	.word @song0ch4loop
